# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ForexFlaresApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for ForexFlaresApp
  pod 'Firebase/Messaging', '~> 5.3.0'
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'
  pod 'Firebase/AdMob', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.3.0'

  target 'ForexFlaresAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ForexFlaresApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ForexFlaresApp-tvOS

end
